---
- name: Check if ipset path is correct
  command: "{{ firewall_ipset_path }} --version"
  register: ipset_help
  ignore_errors: yes
  changed_when: ipset_help.rc != 0

- name: Get ipset path
  command: which ipset
  register: ipset_location
  when: ipset_help is defined and ipset_help.rc != 0

- name: Set found ipset path
  set_fact:
    firewall_ipset_path: "{{ iptables_location.stdout }}"
  when: ipset_help is defined and ipset_location.stdout is defined

- name: Create ipset service file
  template:
    src: ipset.service.j2
    dest: "{{ systemd_unit_directory }}/ipset.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd

- name: Generate ipset file
  template:
    src: ipset.j2
    dest: "{{ conf_file_location }}/ipset"
  notify:
    - stop iptables
    - stop iptables-persistent
    - stop ip6tables
    - stop ip6tables-persistent
    - restart and enable ipset
