---
- name: Check if ipset path is correct
  command: "{{ firewall_ipset_path }} --version"
  register: ipset_help
  ignore_errors: yes

- name: Get ipset path
  command: which ipset
  register: ipset_location
  when: ipset_help is defined and ipset_help.rc != 0

- name: Set found ipset path
  set_fact:
    firewall_ipset_path: "{{ iptables_location.stdout }}"
  when: ipset_help is defined and ipset_location.stdout is defined

- name: Create ipset service file
  copy:
    src: ipset.service
    dest: "/usr/lib/systemd/system/ipset.service"

- name: Generate ipset file
  template:
    src: firewall-ipset.j2
    dest: /etc/sysconfig/ipset-rules
#  notify:
#    - start and enable ipset
