---
- name: Check if ipset path is correct
  command: "{{ firewall_ipset_path }} --help"
  register: ipset_help
  ignore_errors: yes

- name: Get iptables path
  command: which iptables
  register: ipset_location
  when: ipset_help is defined and ipset_help.rc != 0

- name: Set found iptables path
  set_fact:
    firewall_ipset_path: "{{ iptables_location.stdout }}"
  when: ipset_help is defined and ipset_location.stdout is defined

- name: Generate iptables file
  template:
    src: firewall.j2
    dest: /root/firewall
#  notify:
#    - start and enable iptables and ip6tables
#    - start and enable iptables-persistent and ip6tables-persistent
