---
- name: Set systemd_system_unit_directory for debian based systems
  set_fact:
    systemd_system_unit_directory: "/lib/systemd/system"
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Set ipset_conf_path for debian based systems
  set_fact:
    ipset_conf_path: "/etc/default/ipset"
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Check if ipset path is correct
  command: "{{ firewall_ipset_path }} --version"
  register: ipset_help
  ignore_errors: yes

- name: Get ipset path
  command: which ipset
  register: ipset_location
  when: ipset_help is defined and ipset_help.rc != 0

- name: Set found ipset path
  set_fact:
    firewall_ipset_path: "{{ iptables_location.stdout }}"
  when: ipset_help is defined and ipset_location.stdout is defined

- name: Create ipset service file
  copy:
    src: ipset.service
    dest: "{{ systemd_system_unit_directory }}/ipset.service"

- name: Generate ipset file
  template:
    src: firewall-ipset.j2
    dest: /etc/sysconfig/ipset
#  notify:
#    - start and enable ipset
