---
- name: Stop firewalld service
  service:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Mask firewalld service
  systemd:
    name: firewalld
    enabled: no
    masked: yes
  ignore_errors: yes

- name: Ensure firewall_iptables_directory exists
  file:
    state: directory
    path: "{{ firewall_iptables_directory }}"
    owner: root
    group: root
    mode: 0755

- include: ipset.yml

- include: iptables.yml

- name: Install conntrack-tools on Fedora
  package:
    name: conntrack-tools
    state: latest
  when: ansible_distribution == "Fedora"
