---
- name: Stop firewalld service
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: has_firewalld

- name: Mask firewalld service
  command: systemctl mask firewalld.service

- name: Install iptables tools (rhel)
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: "{{ item }}"
    state: latest
  with_items:
    - iptables-services
    - ipset

- include: ipset.yml

- include: iptables.yml
