---
- name: reload systemd
  command: systemctl --system daemon-reload

- name: restart and enable ipset
  service:
    name: "{{ firewall_ipset_service }}"
    state: restarted
    enabled: yes
  when: firewall_ipset_enabled

- name: test iptables
  command: "iptables-restore --test {{ firewall_iptables_directory }}/{{ firewall_iptables_file_name }}"

- name: test ip6tables
  command: "ip6tables-restore --test {{ firewall_iptables_directory }}/{{ firewall_ip6tables_file_name }}"

- name: restart and enable iptables
  service:
    name: "{{ firewall_iptables_service }}"
    state: restarted
    enabled: yes
  when: not firewall_ipset_enabled or firewall_ipset_service != firewall_iptables_service

- name: restart and enable ip6tables
  service:
    name: "{{ firewall_ip6tables_service }}"
    state: restarted
    enabled: yes
  when: firewall_iptables_service != firewall_ip6tables_service
