---
- name: reload systemd
  command: systemctl --system daemon-reload

- name: restart and enable ipset
  service:
    name: "ipset"
    state: restarted
    enabled: yes
  when: firewall_ipset_enabled

- name: start and enable ipset
  service:
    name: "ipset"
    state: started
    enabled: yes
  when: firewall_ipset_enabled and firewall_start_ipset_before_iptables

- name: restart and enable iptables
  service:
    name: iptables
    state: restarted
    enabled: yes
  when: ansible_distribution != "Debian" and ansible_distribution != "Ubuntu"

- name: restart and enable iptables-persistent
  service:
    name: iptables-persistent
    state: restarted
    enabled: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: restart and enable ip6tables
  service:
    name: ip6tables
    state: restarted
    enabled: yes
  when: ansible_distribution != "Debian" and ansible_distribution != "Ubuntu"

- name: restart and enable ip6tables-persistent
  service:
    name: ip6tables-persistent
    state: restarted
    enabled: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: stop iptables
  service:
    name: iptables
    state: restarted
  when: firewall_stop_iptables_before_ipset and ansible_distribution != "Debian" and ansible_distribution != "Ubuntu"

- name: stop iptables-persistent
  service:
    name: iptables-persistent
    state: restarted
  when: firewall_stop_iptables_before_ipset and ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: stop ip6tables
  service:
    name: ip6tables
    state: stopped
  when: firewall_stop_iptables_before_ipset and ansible_distribution != "Debian" and ansible_distribution != "Ubuntu"

- name: stop ip6tables-persistent
  service:
    name: ip6tables-persistent
    state: stop
  when: firewall_stop_iptables_before_ipset and ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
