---
- name: start and enable ipset
  service:
    name: "ipset"
    state: restarted
    enabled: yes

- name: start and enable iptables and ip6tables
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - iptables
    - ip6tables
  when: ansible_distribution != "Debian" and ansible_distribution != "Ubuntu"

- name: start and enable iptables-persistent and ip6tables-persistent
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - iptables-persistent
    - ip6tables-persistent
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
